<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\VehicleBrand; use App\Models\VehicleBodyType; use App\Models\VehicleFuel;
use Illuminate\Http\Request; use Illuminate\Support\Str;
class CarMasterController extends Controller {
 public function index(){return view('admin.car-masters',['brands'=>VehicleBrand::orderBy('sort_order')->orderBy('name')->get(),'bodyTypes'=>VehicleBodyType::orderBy('sort_order')->orderBy('name')->get(),'fuels'=>VehicleFuel::orderBy('sort_order')->orderBy('name')->get()]);}
 public function store(Request $r){$d=$r->validate(['type'=>'required|in:brand,body_type,fuel','name'=>'required|string|max:80','image'=>'nullable|string|max:1000','image_upload'=>'nullable|image|max:6144','sort_order'=>'nullable|integer|min:0|max:65535','vehicle_type'=>'nullable|in:car,bike,truck']);$map=['brand'=>VehicleBrand::class,'body_type'=>VehicleBodyType::class,'fuel'=>VehicleFuel::class];$model=$map[$d['type']];$values=['slug'=>Str::slug($d['name']),'sort_order'=>$d['sort_order']??0];if($d['type']==='body_type')$values['vehicle_type']=$d['vehicle_type']??'car';if($d['type']==='brand'){$values['image']=trim((string)($d['image']??''));if($r->file('image_upload'))$values['image']=$this->storeBrandImage($r->file('image_upload'));}$model::updateOrCreate(['name'=>trim($d['name'])],$values);return back()->with('success','Master value saved.');}
 public function update(Request $r,string $type,int $id){$map=['brand'=>VehicleBrand::class,'body_type'=>VehicleBodyType::class,'fuel'=>VehicleFuel::class];abort_unless(isset($map[$type]),404);$d=$r->validate(['name'=>'required|string|max:80','image'=>'nullable|string|max:1000','image_upload'=>'nullable|image|max:6144','sort_order'=>'nullable|integer|min:0|max:65535']);$item=$map[$type]::findOrFail($id);$values=['name'=>trim($d['name']),'slug'=>Str::slug($d['name']),'sort_order'=>$d['sort_order']??0];if($type==='brand'){if(array_key_exists('image',$d))$values['image']=trim((string)$d['image']);if($r->file('image_upload'))$values['image']=$this->storeBrandImage($r->file('image_upload'));}$item->update($values);return back()->with('success','Master value updated.');}
 private function storeBrandImage($file): string {$folder=public_path('uploads/car-master/brands/'.date('Y/m'));if(!is_dir($folder))mkdir($folder,0755,true);$name=uniqid('brand_',true).'.'.$file->getClientOriginalExtension();$file->move($folder,$name);return asset('uploads/car-master/brands/'.date('Y/m').'/'.$name);}
 public function destroy(Request $r,string $type,int $id){$map=['brand'=>VehicleBrand::class,'body_type'=>VehicleBodyType::class,'fuel'=>VehicleFuel::class];abort_unless(isset($map[$type]),404);$map[$type]::findOrFail($id)->delete();return back()->with('success','Master value removed.');}
}
